### ISSUE TITLE
A single cell tutorial

### ISSUE THREAD

**Issue by yuGithuuub** [data2intelligence/CytoSig#5]
Hi：
  I used scRNA-seq data to compute the cytokine signaling activity with CytoSig.
  But my results are not ideal.I think it might be some data processing details.
  Could you please provide a single cell data and processing flow mentioned in the Nature method article?
  By reproducing the process, I think it can quickly help me find the problem
  Thank you!
Best,
Yu

**Comment by data2intelligence** [comment]
Hi, Yu,

No problem. Let me prepare a mini-example for you and update the Github.


Peng


On May 22, 2022, at 10:15 AM, yuGithuuub ***@***.******@***.***>> wrote:



Hi：
I used scRNA-seq data to compute the cytokine signaling activity with CytoSig.
But my results are not ideal.I think it might be some data processing details.
Could you please provide a single cell data and processing flow mentioned in the Nature method article?
By reproducing the process, I think it can quickly help me find the problem
Thank you!
Best,
Yu

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdata2intelligence%2FCytoSig%2Fissues%2F5&data=05%7C01%7Cpeng.jiang%40nih.gov%7C0274f0fcd61e41ae4d7208da3bfd9934%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637888257628346699%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jVPKfQSfwepYsUlgywNPOKzzVRiYgPTAl92%2B4U3fv0U%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQRREFYXBTZYZR3WMPN4V3DVLI6R7ANCNFSM5WTON5OQ&data=05%7C01%7Cpeng.jiang%40nih.gov%7C0274f0fcd61e41ae4d7208da3bfd9934%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637888257628346699%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kyhclcIF%2FnqAGiwIN5P%2Ft%2FXbSgLPd5v2JFeofQNpCs4%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by yuGithuuub** [comment]
Thanks Peng：
  Due to my privious work has be finished on the R environment, I developed a work flow from a seurat object.
  First I analyzed the differences between CD4 T cell sub-clusters and didn't seem to get very good results.
  However, when I used myeloid-derived cells for my analysis, I got very good results, very consistent with biological effects.
  Very nice tool, I would like to incorporate it into my single cell analysis workbox.
  I guess a friendly tutorial could help more researchers use it.

**Comment by data2intelligence** [comment]
> Thanks Peng： Due to my privious work has be finished on the R environment, I developed a work flow from a seurat object. First I analyzed the differences between CD4 T cell sub-clusters and didn't seem to get very good results. However, when I used myeloid-derived cells for my analysis, I got very good results, very consistent with biological effects. Very nice tool, I would like to incorporate it into my single cell analysis workbox. I guess a friendly tutorial could help more researchers use it.

**Comment by data2intelligence** [comment]
Hi, Yu,

I just changed the CytoSig with an input option using cell ranger output formats. Please see the README file and update source code from Github. I also include an example R code, converting Seurat to count data in cell ranger output in the README. Then, you can run with cell ranger input mode.

Would you please have a try of the new function and tell me if it works for you?



On May 22, 2022, at 12:46 PM, yuGithuuub ***@***.******@***.***>> wrote:



Thanks Peng：
Due to my privious work has be finished on the R environment, I developed a work flow from a seurat object.
First I analyzed the differences between CD4 T cell sub-clusters and didn't seem to get very good results.
However, when I used myeloid-derived cells for my analysis, I got very good results, very consistent with biological effects.
Very nice tool, I would like to incorporate it into my single cell analysis workbox.
I guess a friendly tutorial could help more researchers use it.

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdata2intelligence%2FCytoSig%2Fissues%2F5%23issuecomment-1133932889&data=05%7C01%7Cpeng.jiang%40nih.gov%7Cf9c43cadd92945896c3808da3c128f29%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637888347652325455%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7Rc4nCDxfccbFRWWxWFiK29Mn0yGIxoZRKG4FGl2UW8%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQRREF5NT7LETOUBVMWKRTLVLJQERANCNFSM5WTON5OQ&data=05%7C01%7Cpeng.jiang%40nih.gov%7Cf9c43cadd92945896c3808da3c128f29%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637888347652325455%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=37Bu8084Lb%2B79AbUETb%2Bltvl09DRwiYyDuJknuFwHag%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.
