### ISSUE TITLE
Cytokine activities covid

### ISSUE THREAD

**Issue by ebasto** [data2intelligence/CytoSig#7]
Hi, your paper says 

"For each single-cell dataset, we computed the cytokine activities for individual cells using the CytoSig model and got the mean value for each cell type in each patient."

I was wondering what background you used for severe, early and control. 

That is, did you run cytosig like this (pseudocode):

for cell type 1
for patient 1 (severe)
results = cytosig(severe[patient 1 cell type 1] - control[all patients in control, cell type 1])

if so, **what background did you use for control itself**? also, did you use control as a background for early? 

Thanks!
Edgar

**Comment by data2intelligence** [comment]
Hi, Edgar,

Your understanding is almost correct, except that I only created an overall background control overall all cell types in the healthy patients. In another word, I did start with your cell type specific control first, but then get another mean vector of all cell types and subtract this background from all single-cell expression vectors.

This background mean vector is also the control for the healthy patient groups, which will lead to a lack of statistical significance in the healthy groups in general.

Among datasets analyzed in our original publication, we don’t have early vs late studies. As many COVID19 datasets published later have time points, you may use the "all cells mean” of the early condition for each patient as a control, to see changes that happened after early-onset within each patient. This is just my suggestion, as I have never done this analysis by myself.


Sent from my iPhone

On Jul 1, 2022, at 2:41 AM, ebasto ***@***.******@***.***>> wrote:

﻿


Hi, your paper says

"For each single-cell dataset, we computed the cytokine activities for individual cells using the CytoSig model and got the mean value for each cell type in each patient."

I was wondering what background you used for severe, early and control.

That is, did you run cytosig like this (pseudocode):

for cell type 1
for patient 1 (severe)
results = cytosig(severe[patient 1 cell type 1] - control[all patients in control, cell type 1])

if so, what background did you use for control itself? also, did you use control as a background for early?

Thanks!
Edgar

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdata2intelligence%2FCytoSig%2Fissues%2F7&data=05%7C01%7Cpeng.jiang%40nih.gov%7C6cae3eccb5724e13b22908da5b2cc784%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637922545125132993%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HQ%2B4RGVlwXZt45Lu3PQvmQ82x2%2FDJuToCTQ86H4mhcU%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQRREF7IDPZ2CZX7RQFZ7BTVR2HK3ANCNFSM52LVCUMQ&data=05%7C01%7Cpeng.jiang%40nih.gov%7C6cae3eccb5724e13b22908da5b2cc784%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637922545125132993%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hCJhRf7ig0mNvkZX1ZpZcPv0Q65zTs%2FF3qzYcmKx1iQ%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by ebasto** [comment]
Thank you for the response!

If I understand what you're saying, the pseudocode looks like

for cell type 1
for patient 1 (severe)
results = cytosig(log2(tpm+1)[patient 1 + cell type 1] -geneMeans(log2(tpm+1)[all patients in control + **all cell types**]))

or did you subtract two backgrounds - one cell type specific and one across all cell types (both control).

Thanks,
Edgar

**Comment by data2intelligence** [comment]
Hi, Edgar,

Your understanding is correct. I only subtract one background across all cell types.

Btw, I suggest using log2(TPM/10 + 1) as most single-cell papers use TPM/10 for insufficient sequencing read counts.


Sincerely, Peng


On Jul 1, 2022, at 9:08 PM, ebasto ***@***.******@***.***>> wrote:



Thank you for the response!

If I understand what you're saying, the pseudocode looks like

for cell type 1
for patient 1 (severe)
results = cytosig(log2(tpm+1)[patient 1 + cell type 1] -geneMeans(log2(tpm+1)[all patients in control + all cell types]))

or did you subtract two backgrounds - one cell type specific and one across all cell types (both control).

Thanks,
Edgar

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdata2intelligence%2FCytoSig%2Fissues%2F7%23issuecomment-1172804125&data=05%7C01%7Cpeng.jiang%40nih.gov%7C1a1f0a8b9cca47990ace08da5bc75d5f%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637923209067563616%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zh8JyYfi%2F%2F16YzmnlSlpUhu6ArLEIu2x%2FmsQ3Hsbpxc%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQRREF6LKCSKFBURN66GPA3VR6JAPANCNFSM52LVCUMQ&data=05%7C01%7Cpeng.jiang%40nih.gov%7C1a1f0a8b9cca47990ace08da5bc75d5f%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637923209067563616%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=J%2BHtZdRpfmc%2FhMxrDPnUnKYnOoDe6JB3hBpjchWvdQw%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by ebasto** [comment]
Thank you Peng,

I've attempted what we've discussed and I'm having difficulty getting the same results published in figure 6 g. I'm not exactly sure where I'm going astray, but it would be tremendously helpful if you could share the code through which you got to that figure, I also include my code below:

`
#####functions ----
convertToTPHTLog2P1 <- function(E.matrix){
  size_factor = 1E5/colSums(E.matrix)
  E.matrix = t(E.matrix)*size_factor
  E.matrix = t(E.matrix)
  E.matrix <- log(E.matrix+1,base=2)
  return(E.matrix)
}

substractBackground <- function(E.matrix,background){
  matching.genes <- intersect(rownames(E.matrix),rownames(background))
  E.matrix <- E.matrix[matching.genes,] - background[matching.genes,]
  return(E.matrix)
}

#####input for cytosig -----
#so I downloaded the Processed scRNA-seq count data for pbmcs processed through **10x** platform from fastgenomics (about 99k cells) and I matched them to the cell labels in figure 6d of your paper.

#####background calculation ----
ind.control <- which(covid.19.sc.data$group_per_sample == "control")
E.matrix.control <- covid.19.sc.data@assays$RNA@counts[,ind.control]

ind.0 <- which(rowSums(E.matrix.control) == 0)
E.matrix.control <- E.matrix.control[-ind.0,]
E.matrix.control <- as.matrix(E.matrix.control)

E.matrix.control <- convertToTPHTLog2P1(E.matrix.control)
background <- rowMeans(E.matrix.control)
write.csv(background,file = "background.csv")

#####diff expr. profiles (cell level) ----
 #seurat object corresponding to classical monocytes in severe patients
Seurat <- readRDS("covid_19/E.matrices/severe_Classical Monocytes.rds")
E.matrix <- as.matrix(Seurat@assays$RNA@counts)
control.background <- read.csv("covid_19/background.csv",row.names = 1)

E.matrix <- convertToTPHTLog2P1(E.matrix)
Diff.profile <- substractBackground(E.matrix, control.background)
write.csv(Diff.profile, file="Diff.profile.csv")

#### Running cytosig ----
docker run -it --rm  ebasto/cytosig python CytoSig_run.py -e 1 -i Diff.profile.csv -o output

#### Result comparison ---- 
#(Expecting a somewhat straight line)



`
![Screen Shot 2022-07-04 at 10 27 43 am](https://user-images.githubusercontent.com/12102945/177071010-0ef68fbe-be27-4c0f-9865-5459be547e86.png)

Thanks for your help,

Edgar

**Comment by data2intelligence** [comment]
Hi, Edgar,

Sure, I am creating a Github package (python) to reproduce major results of the CytoSig figures and will make it public. Please wait for my update.


Sincerely, Peng


On Jul 3, 2022, at 10:28 PM, ebasto ***@***.******@***.***>> wrote:



Thank you Peng,

I've attempted what we've discussed and I'm having difficulty getting the same results published in figure 6 g. I'm not exactly sure where I'm going astray, but it would be tremendously helpful if you could share the code through which you got to that figure, I also include my code below:

`
#####functions ----
convertToTPHTLog2P1 <- function(E.matrix){
size_factor = 1E5/colSums(E.matrix)
E.matrix = t(E.matrix)*size_factor
E.matrix = t(E.matrix)
E.matrix <- log(E.matrix+1,base=2)
return(E.matrix)
}

substractBackground <- function(E.matrix,background){
matching.genes <- intersect(rownames(E.matrix),rownames(background))
E.matrix <- E.matrix[matching.genes,] - background[matching.genes,]
return(E.matrix)
}

#####input for cytosig -----
#so I downloaded the Processed scRNA-seq count data for pbmcs processed through 10x platform from fastgenomics (about 99k cells) and I matched them to the cell labels in figure 6d of your paper.

#####background calculation ----
ind.control <- which(covid.19.sc.data$group_per_sample == "control")
E.matrix.control <- ***@***.******@***.***[,ind.control]

ind.0 <- which(rowSums(E.matrix.control) == 0)
E.matrix.control <- E.matrix.control[-ind.0,]
E.matrix.control <- as.matrix(E.matrix.control)

E.matrix.control <- convertToTPHTLog2P1(E.matrix.control)
background <- rowMeans(E.matrix.control)
write.csv(background,file = "background.csv")

#####diff expr. profiles (cell level) ----
#seurat object corresponding to classical monocytes in severe patients
Seurat <- readRDS("covid_19/E.matrices/severe_Classical Monocytes.rds")
E.matrix <- ***@***.******@***.***)
control.background <- read.csv("covid_19/background.csv",row.names = 1)

E.matrix <- convertToTPHTLog2P1(E.matrix)
Diff.profile <- substractBackground(E.matrix, control.background)
write.csv(Diff.profile, file="Diff.profile.csv")

Running cytosig ----

docker run -it --rm ebasto/cytosig python CytoSig_run.py -e 1 -i Diff.profile.csv -o output

Result comparison ----

#(Expecting a somewhat straight line)

`
[Screen Shot 2022-07-04 at 10 27 43 am]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F12102945%2F177071010-0ef68fbe-be27-4c0f-9865-5459be547e86.png&data=05%7C01%7Cpeng.jiang%40nih.gov%7Cb643b551c6ec4ded9bb308da5d64dfe3%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637924985117358341%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9LFk3y3XqNk5HDvf1MOK36CmZfS65VIqg0626yHkEHQ%3D&reserved=0>

Thanks for your help,

Edgar

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdata2intelligence%2FCytoSig%2Fissues%2F7%23issuecomment-1173271825&data=05%7C01%7Cpeng.jiang%40nih.gov%7Cb643b551c6ec4ded9bb308da5d64dfe3%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637924985117358341%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mmypbLI1kxQzIGsn1CKGkwc8gyOOAF9wsjts2oy6%2BIc%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQRREF5ZN7LZ3UUXZJ3LGPDVSJD4RANCNFSM52LVCUMQ&data=05%7C01%7Cpeng.jiang%40nih.gov%7Cb643b551c6ec4ded9bb308da5d64dfe3%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637924985117358341%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=i8Fz7htd9OMw48Zy%2FDbB7YBUrfFH%2BQYu%2BdBbS3jIw88%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by ebasto** [comment]
Thanks Peng!

Edgar

**Comment by data2intelligence** [comment]
Hi, Edgar,

Please see my new Github projects on reproducing major results in the Figure 4 and 6. https://github.com/data2intelligence/CytoSig_prediction. I also inserted the link in the CytoSig README file.

I am not familiar with R and only use Python. This package should enable you to repeat my results starting from the release files from the original study. Let me know if it answers your question.



Sincerely, Peng


On Jul 3, 2022, at 10:38 PM, ebasto ***@***.******@***.***>> wrote:



Thanks Peng!

Edgar

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdata2intelligence%2FCytoSig%2Fissues%2F7%23issuecomment-1173276166&data=05%7C01%7Cpeng.jiang%40nih.gov%7Cf01a6a6afe9246c33ff908da5d664991%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637924991169038281%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Y9g35ISsm5HNmRhZm65QS%2FrDsgF055uXzXgtJ1WompE%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQRREFY6VPLUEF3Y3E7LJBTVSJFCNANCNFSM52LVCUMQ&data=05%7C01%7Cpeng.jiang%40nih.gov%7Cf01a6a6afe9246c33ff908da5d664991%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637924991169038281%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3NORnxH968JL7H87oe7Efg%2ByUh8Ox6R31g4UxF6LkpY%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by ebasto** [comment]
Thank you Peng!

This was super useful! I found an error in my code, hence why I wasn't getting the same results as you. I've fixed it and now there is agreement.

Best Regards,
Edgar

![Screen Shot 2022-07-08 at 11 00 55 am](https://user-images.githubusercontent.com/12102945/177908562-03a1dd65-394f-42af-bfb8-3cb51ea17e3b.png)

**Comment by data2intelligence** [comment]
Sure, Glad to help ^_^


Peng


On Jul 7, 2022, at 11:02 PM, ebasto ***@***.******@***.***>> wrote:



Thank you Peng!

This was super useful! I found an error in my code, hence why I wasn't getting the same results as you. I've fixed it and now there is agreement.

Best Regards,
Edgar

[Screen Shot 2022-07-08 at 11 00 55 am]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F12102945%2F177908562-03a1dd65-394f-42af-bfb8-3cb51ea17e3b.png&data=05%7C01%7Cpeng.jiang%40nih.gov%7C4f5c3e459ca14d4ff28e08da608e41d2%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637928461361127433%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7HXpOkrUv8PGx16PEMelKTd2VkCsNKpfE2Wz14ppuBU%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdata2intelligence%2FCytoSig%2Fissues%2F7%23issuecomment-1178488273&data=05%7C01%7Cpeng.jiang%40nih.gov%7C4f5c3e459ca14d4ff28e08da608e41d2%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637928461361127433%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=N46dY0FcTv93nYBkTlEhoN7NPCHyt3TfCWkoU1KL%2F7k%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQRREFYQTBUS3EC2ZNQWXSDVS6K3FANCNFSM52LVCUMQ&data=05%7C01%7Cpeng.jiang%40nih.gov%7C4f5c3e459ca14d4ff28e08da608e41d2%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637928461361127433%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4%2B99nYomw4UibsCTPgscJw1aDELZCbfJNxfJDLINJ00%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.
