### ISSUE TITLE
Issues prepping the environment - Docker request

### ISSUE THREAD

**Issue by FredoJones** [data2intelligence/CytoSig#8]
Greetings, 
Thank you for the amazing tool. 
I have been trying to set this up multiple times both on my local machine and a on HPC facility. However it is still a problem to recover and make available gsl and its libraries. I have looked at the previous issue on this topic but i could not solve it with the advice found in there. I was wondering if this application will be ever made available on a docker/singularity solution, in order to bypass these tedious issues. 
Greetings 
FJ

**Comment by data2intelligence** [comment]
Hi, FJ,

Very good suggestion! I will look into the Docker solution and let you know once it is ready.

Happy holidays.


Sincerely, Peng


On Dec 23, 2022, at 7:15 AM, FredoJones ***@***.******@***.***>> wrote:

﻿


Greetings,
Thank you for the amazing tool.
I have been trying to set this up multiple times both on my local machine and a on HPC facility. However it is still a problem to recover and make available gsl and its libraries. I have looked at the previous issue on this topic but i could not solve it with the advice found in there. I was wondering if this application will be ever made available on a docker/singularity solution, in order to bypass these tedious issues.
Greetings
FJ

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdata2intelligence%2FCytoSig%2Fissues%2F8&data=05%7C01%7Cpeng.jiang%40nih.gov%7C8af1e44c7bc244f53ab008dae4df707c%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638073945557176731%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qyNP9YT5EEPsUJU4LYxwfG9BqhYwNxIDpu3%2BHP%2BWZ8Y%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQRREF3PKGLT2S5BXCTCNNDWOWJXRANCNFSM6AAAAAATHVVUVY&data=05%7C01%7Cpeng.jiang%40nih.gov%7C8af1e44c7bc244f53ab008dae4df707c%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638073945557176731%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DCiwzmMIf9Mszj7laMBlnrYhLYYfqO2vlhiMSEFSxBU%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by data2intelligence** [comment]
Hi, FJ,
Please see the updated CytoSig code and README file, and try the Docker solution. Let me know if the Docker image works for you.

**Comment by FredoJones** [comment]
Works like a charm. Thank you so much for everything! 

> Hi, FJ, Please see the updated CytoSig code and README file, and try the Docker solution. Let me know if the Docker image works for you.
